volumes:
  servervol:
  clientvol:

services:
  server:
    build:
      context: E:\Dicecamp\Devops\final project\part 1\Server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - servervol:/serverdata
    networks:
      - default

  client:
    build:
      context: E:\Dicecamp\Devops\final project\part 1\Client
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - clientvol:/clientdata
    depends_on:
      - server
    networks:
      - default
