name: Server Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push image
        run: |
          docker build -t my-server-image .
          docker tag my-server-image my-docker-hub-username/my-server-image:latest
          docker push my-docker-hub-username/my-server-image:latest
