name: Server Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set environment variables
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker login
        run: |
          docker login -u awais -p $DOCKER_PASSWORD
      - name: Build and push image
        run: |
          docker build -t my-server-image -f Dockerfile .
          docker tag my-server-image awaismehmodbaig/my-server-image:latest
          docker push awaismehmodbaig/my-server-image:latest
